/* eslint-disable spellcheck/spell-checker */

const programmingLanguages = [
    { title: '1C', value: '1c' },
    { title: '4D', value: '4d' },
    { title: 'ABAP', value: 'sap-abap' },
    { title: 'ABNF', value: 'abnf' },
    { title: 'Access logs', value: 'accesslog' },
    { title: 'Ada', value: 'ada' },
    { title: 'Apex', value: 'apex' },
    { title: 'Arduino', value: 'arduino' },
    { title: 'ARM assembler', value: 'armasm' },
    { title: 'AVR assembler', value: 'avrasm' },
    { title: 'ActionScript', value: 'actionscript' },
    { title: 'Alan IF', value: 'alan' },
    { title: 'Alan', value: 'ln' },
    { title: 'AngelScript', value: 'angelscript' },
    { title: 'Apache', value: 'apache' },
    { title: 'AppleScript', value: 'applescript' },
    { title: 'Arcade', value: 'arcade' },
    { title: 'AsciiDoc', value: 'asciidoc' },
    { title: 'AspectJ', value: 'aspectj' },
    { title: 'AutoHotkey', value: 'autohotkey' },
    { title: 'AutoIt', value: 'autoit' },
    { title: 'Awk', value: 'awk' },
    { title: 'Bash', value: 'bash' },
    { title: 'Basic', value: 'basic' },
    { title: 'BBCode', value: 'bbcode' },
    { title: 'Blade (Laravel)', value: 'blade' },
    { title: 'BNF', value: 'bnf' },
    { title: 'Brainfuck', value: 'brainfuck' },
    { title: 'C#', value: 'csharp' },
    { title: 'C', value: 'c' },
    { title: 'C++', value: 'cpp' },
    { title: 'C/AL', value: 'cal' },
    { title: 'Cache Object Script', value: 'cos' },
    { title: 'CMake', value: 'cmake' },
    { title: 'COBOL', value: 'cobol' },
    { title: 'Coq', value: 'coq' },
    { title: 'CSP', value: 'csp' },
    { title: 'CSS', value: 'css' },
    { title: 'Cap’n Proto', value: 'capnproto' },
    { title: 'Chaos', value: 'chaos' },
    { title: 'Chapel', value: 'chapel' },
    { title: 'Cisco CLI', value: 'cisco' },
    { title: 'Clojure', value: 'clojure' },
    { title: 'CoffeeScript', value: 'coffeescript' },
    { title: 'CpcdosC+', value: 'cpc' },
    { title: 'Crmsh', value: 'crmsh' },
    { title: 'Crystal', value: 'crystal' },
    { title: 'cURL', value: 'curl' },
    { title: 'Cypher (Neo4j)', value: 'cypher' },
    { title: 'D', value: 'd' },
    { title: 'Dafny', value: 'dafny' },
    { title: 'Dart', value: 'dart' },
    { title: 'Delphi', value: 'dpr' },
    { title: 'Diff', value: 'diff' },
    { title: 'Django', value: 'django' },
    { title: 'DNS Zone file', value: 'dns' },
    { title: 'Dockerfile', value: 'dockerfile' },
    { title: 'DOS', value: 'dos' },
    { title: 'dsconfig', value: 'dsconfig' },
    { title: 'DTS (Device Tree)', value: 'dts' },
    { title: 'Dust', value: 'dust' },
    { title: 'Dylan', value: 'dylan' },
    { title: 'EBNF', value: 'ebnf' },
    { title: 'Elixir', value: 'elixir' },
    { title: 'Elm', value: 'elm' },
    { title: 'Erlang', value: 'erlang' },
    { title: 'Excel', value: 'excel' },
    { title: 'Extempore', value: 'extempore' },
    { title: 'F#', value: 'fsharp' },
    { title: 'FIX', value: 'fix' },
    { title: 'Fortran', value: 'fortran' },
    { title: 'G-Code', value: 'gcode' },
    { title: 'Gams', value: 'gams' },
    { title: 'GAUSS', value: 'gauss' },
    { title: 'GDScript', value: 'godot' },
    { title: 'Gherkin', value: 'gherkin' },
    { title: 'Glimmer and EmberJS', value: 'hbs' },
    { title: 'GN for Ninja', value: 'gn' },
    { title: 'Go', value: 'go' },
    { title: 'Grammatical Framework', value: 'gf' },
    { title: 'Golo', value: 'golo' },
    { title: 'Gradle', value: 'gradle' },
    { title: 'GraphQL', value: 'graphql' },
    { title: 'Groovy', value: 'groovy' },
    { title: 'GSQL', value: 'gsql' },
    { title: 'HTML / XML', value: 'xml' },
    { title: 'HTTP', value: 'http' },
    { title: 'Haml', value: 'haml' },
    { title: 'Handlebars', value: 'handlebars' },
    { title: 'Haskell', value: 'haskell' },
    { title: 'Haxe', value: 'haxe' },
    { title: 'High-level shader language', value: 'hlsl' },
    { title: 'Hy', value: 'hy' },
    { title: 'Ini / TOML', value: 'ini' },
    { title: 'Inform7', value: 'inform7' },
    { title: 'IRPF90', value: 'irpf90' },
    { title: 'JSON', value: 'json' },
    { title: 'Java', value: 'java' },
    { title: 'JavaScript', value: 'javascript' },
    { title: 'Jolie', value: 'jolie' },
    { title: 'Julia', value: 'julia' },
    { title: 'Kotlin', value: 'kotlin' },
    { title: 'LaTeX', value: 'tex' },
    { title: 'Leaf', value: 'leaf' },
    { title: 'Lean', value: 'lean' },
    { title: 'Lasso', value: 'lasso' },
    { title: 'Less', value: 'less' },
    { title: 'LDIF', value: 'ldif' },
    { title: 'Lisp', value: 'lisp' },
    { title: 'LiveCode Server', value: 'livecodeserver' },
    { title: 'LiveScript', value: 'livescript' },
    { title: 'Lua', value: 'lua' },
    { title: 'Macaulay2', value: 'macaulay2' },
    { title: 'Makefile', value: 'makefile' },
    { title: 'Markdown', value: 'markdown' },
    { title: 'Mathematica', value: 'mathematica' },
    { title: 'Matlab', value: 'matlab' },
    { title: 'Maxima', value: 'maxima' },
    { title: 'Maya Embedded Language', value: 'mel' },
    { title: 'Mercury', value: 'mercury' },
    { title: 'mIRC Scripting Language', value: 'mirc' },
    { title: 'Mizar', value: 'mizar' },
    { title: 'MKB', value: 'mkb' },
    { title: 'MLIR', value: 'mlir' },
    { title: 'Mojolicious', value: 'mojolicious' },
    { title: 'Monkey', value: 'monkey' },
    { title: 'Moonscript', value: 'moonscript' },
    { title: 'N1QL', value: 'n1ql' },
    { title: 'NSIS', value: 'nsis' },
    { title: 'Never', value: 'never' },
    { title: 'Nginx', value: 'nginx' },
    { title: 'Nim', value: 'nim' },
    { title: 'Nix', value: 'nix' },
    { title: 'Oak', value: 'oak' },
    { title: 'Object Constraint Language', value: 'ocl' },
    { title: 'OCaml', value: 'ocaml' },
    { title: 'Objective C', value: 'objectivec' },
    { title: 'OpenGL Shading Language', value: 'glsl' },
    { title: 'OpenSCAD', value: 'openscad' },
    { title: 'Oracle Rules Language', value: 'ruleslanguage' },
    { title: 'Oxygene', value: 'oxygene' },
    { title: 'PF', value: 'pf' },
    { title: 'PHP', value: 'php' },
    { title: 'Papyrus', value: 'papyrus' },
    { title: 'Parser3', value: 'parser3' },
    { title: 'Perl', value: 'perl' },
    { title: 'Pine Script', value: 'pine' },
    { title: 'Plaintext', value: 'plaintext' },
    { title: 'Pony', value: 'pony' },
    { title: 'PostgreSQL & PL/pgSQL', value: 'pgsql' },
    { title: 'PowerShell', value: 'powershell' },
    { title: 'Processing', value: 'processing' },
    { title: 'Prolog', value: 'prolog' },
    { title: 'Properties', value: 'properties' },
    { title: 'Protocol Buffers', value: 'protobuf' },
    { title: 'Puppet', value: 'puppet' },
    { title: 'Python', value: 'python' },
    { title: 'Python profiler results', value: 'profile' },
    { title: 'Python REPL', value: 'python-repl' },
    { title: 'Q#', value: 'qsharp' },
    { title: 'Q', value: 'k' },
    { title: 'QML', value: 'qml' },
    { title: 'R', value: 'r' },
    { title: 'Razor CSHTML', value: 'cshtml' },
    { title: 'ReasonML', value: 'reasonml' },
    { title: 'Rebol & Red', value: 'redbol' },
    { title: 'RenderMan RIB', value: 'rib' },
    { title: 'RenderMan RSL', value: 'rsl' },
    { title: 'RiScript', value: 'risc' },
    { title: 'Roboconf', value: 'graph' },
    { title: 'Robot Framework', value: 'robot' },
    { title: 'RPM spec files', value: 'rpm-specfile' },
    { title: 'Ruby', value: 'ruby' },
    { title: 'Rust', value: 'rust' },
    { title: 'SAS', value: 'SAS' },
    { title: 'SCSS', value: 'scss' },
    { title: 'SQL', value: 'sql' },
    { title: 'STEP Part 21', value: 'p21' },
    { title: 'Scala', value: 'scala' },
    { title: 'Scheme', value: 'scheme' },
    { title: 'Scilab', value: 'scilab' },
    { title: 'Shape Expressions', value: 'shexc' },
    { title: 'Shell', value: 'shell' },
    { title: 'Smali', value: 'smali' },
    { title: 'Smalltalk', value: 'smalltalk' },
    { title: 'SML', value: 'sml' },
    { title: 'Solidity', value: 'solidity' },
    { title: 'Splunk SPL', value: 'spl' },
    { title: 'Stan', value: 'stan' },
    { title: 'Stata', value: 'stata' },
    { title: 'Structured Text', value: 'iecst' },
    { title: 'Stylus', value: 'stylus' },
    { title: 'SubUnit', value: 'subunit' },
    { title: 'Supercollider', value: 'supercollider' },
    { title: 'Svelte', value: 'svelte' },
    { title: 'Swift', value: 'swift' },
    { title: 'Tcl', value: 'tcl' },
    { title: 'Terraform (HCL)', value: 'terraform' },
    { title: 'Test Anything Protocol', value: 'tap' },
    { title: 'Thrift', value: 'thrift' },
    { title: 'Toit', value: 'toit' },
    { title: 'TP', value: 'tp' },
    { title: 'Transact-SQL', value: 'tsql' },
    { title: 'Twig', value: 'twig' },
    { title: 'TypeScript', value: 'typescript' },
    { title: 'Unicorn Rails log', value: 'unicorn-rails-log' },
    { title: 'VB.Net', value: 'vbnet' },
    { title: 'VBA', value: 'vba' },
    { title: 'VBScript', value: 'vbscript' },
    { title: 'VHDL', value: 'vhdl' },
    { title: 'Vala', value: 'vala' },
    { title: 'Verilog', value: 'verilog' },
    { title: 'Vim Script', value: 'vim' },
    { title: 'X#', value: 'xsharp' },
    { title: 'X++', value: 'axapta' },
    { title: 'x86 Assembly', value: 'x86asm' },
    { title: 'XL', value: 'xl' },
    { title: 'XQuery', value: 'xquery' },
    { title: 'YAML', value: 'yml' },
    { title: 'ZenScript', value: 'zenscript' },
    { title: 'Zephir', value: 'zephir' },
]

export default programmingLanguages
